### PR TITLE
[rtl_biast] Fix compile library target and installation

### PR DESCRIPTION
**Pull request by erikarn**
* add rtl_biast target;
* add rtl_biast to the installation targets.

### CODE REVIEW

**Comment by steve-m** [comment]
This has already been fixed in master with 849f8efca42b659bf7e8fe17156ee0aa67b47233.

**Comment by erikarn** [comment]
rtl_biast wasn't merged in though to the command list at the end of src/CMakeLists.txt

**Comment by erikarn** [comment]
This bit:

-install(TARGETS rtl_sdr rtl_tcp rtl_test rtl_fm rtl_eeprom rtl_adsb rtl_power
+install(TARGETS rtl_sdr rtl_tcp rtl_test rtl_fm rtl_eeprom rtl_adsb rtl_power rtl_biast
  DESTINATION ${CMAKE_INSTALL_BINDIR}
  )

**Comment by steve-m** [comment]
Thanks, added it.

**Pull request closed without merging**
